[안은노] 게임로직 구현하기
softeerbootcamp-2nd/ios-luckycardgame pull request #63
Opened 2023-07-12 12:11 UTC by Eunno-An

# 학습 및 요구사항
- 테스트 기반 개발 배경의 등장에 관한 학습
- Test Double(Dummy, Stub, Mock)
- Red/Green/Refactoring 기반 테스트 코드 작성방법 학습
- LuckyCardGame의 XCTest 단위 테스트 구현

# 작업 결과물
|기능|스크린샷|완성시간|
 |:--:|:--:|:--:|
 |테스트 결과|<img width="648" alt="image" src="https://github.com/softeerbootcamp-2nd/ios-luckycardgame/assets/33450365/c14c29a7-42b9-4e6c-8c6e-97b815655e39">|2023.07.12 18:00|

# 작업 내용
- 테스트 코드를 최대한 간결하게 작성했습니다.
- LuckyCardGame에 테스트에 필요한 함수를 작성하지 않고 이와 최대한 유사한클래스인 Mock 클래스를 만들고, LuckyCardGame을 상속받았습니다.
- Mock이 필요한곳과 Stub이 필요한 곳을 나눠서 필요한 Test Double만 사용하도록 작성했습니다.
- 모든 참가자의 카드 배열을 순회하면서, 세개의 중복된 숫자 카드를 갖고있는지 검사하는 코드를 작성했습니다. 만약 한명이라도 세개의 중복된 숫자를 갖고 있다면 assert를 던집니다.
- 마지막으로, 어떤 차례의 플레이어와, 이 플레이어가 룰에 따라서 카드를 뽑고, 세장이 완성되는지 안되는지 검사하는 테스트코드를 작성했습니다.

# 느낀점
- ~~마지막 요구사항에 해당하는 테스트코드를 작성하면서, 뭔가 사용자가 어떤 선택을 할 지 모르니, 랜덤의 개념을 테스트코드 작성할 때 도입해야되는 건가요?~~
- ~~현재는 사용자 선택 케이스가 작다보니, 단순히 모든 경우를 고려해서 if - else문을 사용하여 구현했지만, 좋은 테스트코드는 아닌 것 같다는 생각이 들었습니다.~~
- ~~그리고 debug view hierarchy와, bottom board width의 실제 값이 다르게 나오는 이유를 계속 찾고있지만, 아직 정답을 잘 모르겠습니다. 실제로 debug view hierarchy에서는 width가 353이 나오지만, console에 print한 값은 363이 나옵니다.~~
- 테스트코드를 다시 학습하다보니, if-else같은 문이나, for문을 사용하거나 random을 사용하다보면 이건 테스트코드가 추구하는 방향과 벗어나는 것임을 알게되었습니다.
- 왜냐하면 저렇게 분기처리나 랜덤을 사용하면 어디서 왜 에러가 나는것임을 파악하기 힘들고, FIRST원칙 중.  Repeatable원칙에 어긋나는것임을 알게되었습니다.
- 최대한 간결하게, 시나리오를 정해서 하는것이 테스트 코드를 작성하는 방법이고 명세서 같은 느낌으로 작성하려고 시도했습니다.

2023-07-13 00:31 UTC, godrm requested changes
테스트 코드쪽에 꼭 고치서야 할 게 있어서 머지하지 않고 있을게요
테스트 코드만 개선해서 커밋하고 푸시까지만 하시면 반영될 겁니다. 
수정하시고 나서 코멘트 남겨주세요

2023-07-13 00:31 UTC, godrm commented on LuckyCardGame/LuckyCardGame/Model/AboutPlayer/Attendee.swift
> +}
참가자 이름 같은건 enum타입은 별로 같아요
문제에는 충분하지만요.

2023-07-13 00:31 UTC, godrm commented on LuckyCardGame/LuckyCardGame/Model/AboutPlayer/Attendee.swift
> +        }
위에 타입이 있는데도 결국 하드코딩한거면 둘 다 사용되지 못하는 것 같아요

2023-07-13 00:31 UTC, godrm commented on LuckyCardGame/LuckyCardGame/Model/Mock/Mock.swift
> +    }
mock 객체는 Game을 상속하면 안되고 독립적이어야 합니다
Mock을 호출하도록 만들려면 인터페이스가 동일하면 되서 프로토콜을 사용하는 걸 추천합니다

2023-07-13 00:31 UTC, godrm commented on LuckyCardGame/LuckyCardGame/Model/Mock/Mock.swift
> +        }
최대한 비슷하게 구현하는 시도가 인상적입니다
알고리즘이 중요한 경우는 이렇게 테스트하기도 합니다

2023-07-13 00:31 UTC, godrm commented on LuckyCardGame/LuckyCardGameTests/LuckyCardGameTests.swift
> +        XCTAssertTrue(symbolCheckingFlag, "카드의 동물이 잘못 분배되어있습니다.")
테스트 대상과 Mock을 헷갈리신 것 같아요
테스트 대상이 game이라면 그 대상 자체는 그대로 인스턴스를 만들고 나머지 연관된 타입을 mock으로 대체해서 테스트해야 합니다. 
지금처럼 game을 mock으로 구현하시면 실제 코드르 테스트하는 게 아니니까요

2023-07-13 04:58 UTC, Eunno-An commented
Mock객체를 LuckyCardGame을 상속받아서 만드는게 아닌, stub처럼 전체에서 필요한 부분만 따로 만들어주었습니다.
LuckyCardGame의 Attendee와 비슷한 PlayerMock객체를 만들어서 비교했습니다.
그 외에도 불필요한 Enum을 코드에서 삭제했습니다.

리뷰 감사드립니다!😀

2023-07-14 02:20 UTC, godrm commented on LuckyCardGame/LuckyCardGameTests/LuckyCardGameTests.swift
> +        realAttendee.sortDeckByNumberASC()
realAttendee는 테스트 대상(SUT)이라는 표현을 많이 쓰고, 이렇게 비교 대상이 되는 것은 mock이라고 부르지 않습니다
mock은 직접적으로 SUT에 주입하게 되는 Deck을 대체하는 역할이어야 합니다. 참고하세요

2023-07-14 02:20 UTC, merged